In [72]:
# installing the essential libraries
!pip install PyPDF2 mysql-connector-python

Requirement already satisfied: PyPDF2 in c:\users\asus\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: mysql-connector-python in c:\users\asus\anaconda3\lib\site-packages (9.0.0)

## Task1 :- Extraction of pdf file

In [74]:
import PyPDF2

def extraction_of_pdf_to_text(path):
  
    # Extract text from a PDF file and return it as a list of lines.
    
    # Parameters:
    # path (str): The file path of the PDF document.

    # Returns:
    # list: A list containing each line of extracted text from the PDF.

    
    # Open the PDF file in binary read mode
    with open(path, 'rb') as pdf_file:
        # Create a PdfReader object to read the PDF
        reader = PyPDF2.PdfReader(pdf_file)
        
        # Initialize an empty string to accumulate the extracted text
        text = ""
        
        # Iterate through each page in the PDF
        for page_num in range(len(reader.pages)):
            # Get the specific page object using the page number
            page = reader.pages[page_num]
            
            # Extract text from the current page and append it to the text variable
            text += page.extract_text() or ""  # Use or "" to avoid NoneType errors
            
        # Split the accumulated text into lines and return as a list
        return text.split("\n")  # Split text into lines based on newline characters

In [75]:
to_text = extraction_of_pdf_to_text("sample_bank_statement.pdf")
print(to_text)

['Zenith National Cooperative Bank', 'Reg. No. : ZNC/BLR/RSR/CR/159/03', 'Branch : Indiranagar', 'Statement Of Saving Account', 'Current Date : 30/06/2025', 'Transaction Details From Date : 01/01/2025 To Date : 30/06/2025', 'Name : MEHT A ARYAN DEVENDRA', 'JOINTHOLDER1 : MEHT A PRIY A ARYAN', 'A/c No. : 7024186', 'A/c Start Date : 15/09/2020', 'Interest Rate % : 4.75', 'IFSC Code : ZNCB0004567', 'Address : EVERGREEN RESIDENCY , FLA T 604, 12TH MAIN, INDIRANAGAR, BANGALORE', 'Mobile No.: 9876543210', 'Date Particular Debit Credit Balance', '01/01/2025 Opening Balance 0.00 0.00 52,415.75 Cr', '02/01/2025 TO TRF UPI/New Year Party Expenses 3,500.00 0.00 48,915.75 Cr', '05/01/2025 BY TRF Salary Credit 0.00 65,000.00 113,915.75 Cr', '07/01/2025 TO TRF UPI/Grocery Shopping 2,800.00 0.00 111,115.75 Cr', '10/01/2025 TO TRF Rent Payment 25,000.00 0.00 86,115.75 Cr', '12/01/2025 TO TRF UPI/Electricity Bill 1,850.00 0.00 84,265.75 Cr', '15/01/2025 TO TRF Credit Card Bill 12,500.00 0.00 71,765.75 Cr', '18/01/2025 TO TRF UPI/Dining Out 2,200.00 0.00 69,565.75 Cr', '20/01/2025 TO TRF UPI/Mobile Recharge 999.00 0.00 68,566.75 Cr', '25/01/2025 TO TRF UPI/Online Shopping 3,500.00 0.00 65,066.75 Cr', '28/01/2025 TO TRF UPI/Gym Membership 2,000.00 0.00 63,066.75 Cr', '31/01/2025 BY TRF Interest Credit 0.00 249.00 63,315.75 Cr', '02/02/2025 TO TRF UPI/W eekend Getaway 5,500.00 0.00 57,815.75 Cr', '05/02/2025 BY TRF Salary Credit 0.00 65,000.00 122,815.75 Cr', '07/02/2025 TO TRF UPI/Grocery Shopping 3,200.00 0.00 119,615.75 Cr', '10/02/2025 TO TRF Rent Payment 25,000.00 0.00 94,615.75 Cr', '12/02/2025 TO TRF Insurance Premium 8,500.00 0.00 86,115.75 Cr', '15/02/2025 TO TRF Credit Card Bill 15,000.00 0.00 71,115.75 Cr', "18/02/2025 TO TRF UPI/V alentine's Day Gift 4,000.00 0.00 67,115.75 Cr", '20/02/2025 TO TRF UPI/Car Service 3,500.00 0.00 63,615.75 Cr', '23/02/2025 BY TRF UPI/Freelance W ork 0.00 10,000.00 73,615.75 Cr', '25/02/2025 TO TRF UPI/Home Decor Items 6,000.00 0.00 67,615.75 Cr', '28/02/2025 BY TRF Interest Credit 0.00 267.00 67,882.75 Cr', '02/03/2025 TO TRF UPI/Movie Night 1,500.00 0.00 66,382.75 Cr', '05/03/2025 BY TRF Salary Credit 0.00 65,000.00 131,382.75 Cr', '07/03/2025 TO TRF UPI/Grocery Shopping 3,500.00 0.00 127,882.75 Cr', '10/03/2025 TO TRF Rent Payment 25,000.00 0.00 102,882.75 Cr', '12/03/2025 TO TRF UPI/Electricity Bill 2,100.00 0.00 100,782.75 Cr', '15/03/2025 TO TRF Car Loan EMI 18,500.00 0.00 82,282.75 Cr', '18/03/2025 TO TRF UPI/Birthday Gift 2,500.00 0.00 79,782.75 Cr', '20/03/2025 TO TRF UPI/Online Shopping 7,250.00 0.00 72,532.75 CrDate Particular Debit Credit Balance', '23/03/2025 TO TRF UPI/Dental Appointment 3,000.00 0.00 69,532.75 Cr', '25/03/2025 BY TRF Tax Refund 0.00 8,500.00 78,032.75 Cr', '28/03/2025 TO TRF UPI/Home Repairs 4,500.00 0.00 73,532.75 Cr', '31/03/2025 BY TRF Interest Credit 0.00 290.00 73,822.75 Cr', '02/04/2025 TO TRF UPI/Charity Donation 2,000.00 0.00 71,822.75 Cr', '05/04/2025 BY TRF Salary Credit 0.00 68,000.00 139,822.75 Cr', '07/04/2025 TO TRF UPI/Grocery Shopping 3,800.00 0.00 136,022.75 Cr', '10/04/2025 TO TRF Rent Payment 25,000.00 0.00 111,022.75 Cr', '12/04/2025 TO TRF UPI/Electricity Bill 2,300.00 0.00 108,722.75 Cr', '15/04/2025 TO TRF Credit Card Bill 20,000.00 0.00 88,722.75 Cr', '18/04/2025 TO TRF UPI/New Smartphone 15,000.00 0.00 73,722.75 Cr', '20/04/2025 TO TRF UPI/W edding Gift 5,000.00 0.00 68,722.75 Cr', '23/04/2025 BY TRF UPI/Freelance W ork 0.00 12,000.00 80,722.75 Cr', '25/04/2025 TO TRF UPI/Home Appliance 8,000.00 0.00 72,722.75 Cr', '28/04/2025 TO TRF UPI/Car Insurance 6,500.00 0.00 66,222.75 Cr', '30/04/2025 BY TRF Interest Credit 0.00 261.00 66,483.75 Cr', '02/05/2025 TO TRF UPI/W eekend Trip 7,000.00 0.00 59,483.75 Cr', '05/05/2025 BY TRF Salary Credit 0.00 68,000.00 127,483.75 Cr', '07/05/2025 TO TRF UPI/Grocery Shopping 4,000.00 0.00 123,483.75 Cr', '10/05/2025 TO TRF Rent Payment 25,000.00 0.00 98,483.75 Cr', '12/05/2025 TO TRF Family V acation Expenses 75,000.00 0.00 23']

## Removing initial rows that are not required

In [77]:
def remove_first_rows(lines, num_rows):
    return lines[num_rows:]
pdf_lines_cleaned = remove_first_rows(to_text, 15)
pdf_lines_cleaned

['01/01/2025 Opening Balance 0.00 0.00 52,415.75 Cr',
 '02/01/2025 TO TRF UPI/New Year Party Expenses 3,500.00 0.00 48,915.75 Cr',
 '05/01/2025 BY TRF Salary Credit 0.00 65,000.00 113,915.75 Cr',
 '07/01/2025 TO TRF UPI/Grocery Shopping 2,800.00 0.00 111,115.75 Cr',
 '10/01/2025 TO TRF Rent Payment 25,000.00 0.00 86,115.75 Cr',
 '12/01/2025 TO TRF UPI/Electricity Bill 1,850.00 0.00 84,265.75 Cr',
 '15/01/2025 TO TRF Credit Card Bill 12,500.00 0.00 71,765.75 Cr',
 '18/01/2025 TO TRF UPI/Dining Out 2,200.00 0.00 69,565.75 Cr',
 '20/01/2025 TO TRF UPI/Mobile Recharge 999.00 0.00 68,566.75 Cr',
 '25/01/2025 TO TRF UPI/Online Shopping 3,500.00 0.00 65,066.75 Cr',
 '28/01/2025 TO TRF UPI/Gym Membership 2,000.00 0.00 63,066.75 Cr',
 '31/01/2025 BY TRF Interest Credit 0.00 249.00 63,315.75 Cr',
 '02/02/2025 TO TRF UPI/W eekend Getaway 5,500.00 0.00 57,815.75 Cr',
 '05/02/2025 BY TRF Salary Credit 0.00 65,000.00 122,815.75 Cr',
 '07/02/2025 TO TRF UPI/Grocery Shopping 3,200.00 0.00 119,615.75 Cr',
 '10/02/2025 TO TRF Rent Payment 25,000.00 0.00 94,615.75 Cr',
 '12/02/2025 TO TRF Insurance Premium 8,500.00 0.00 86,115.75 Cr',
 '15/02/2025 TO TRF Credit Card Bill 15,000.00 0.00 71,115.75 Cr',
 "18/02/2025 TO TRF UPI/V alentine's Day Gift 4,000.00 0.00 67,115.75 Cr",
 '20/02/2025 TO TRF UPI/Car Service 3,500.00 0.00 63,615.75 Cr',
 '23/02/2025 BY TRF UPI/Freelance W ork 0.00 10,000.00 73,615.75 Cr',
 '25/02/2025 TO TRF UPI/Home Decor Items 6,000.00 0.00 67,615.75 Cr',
 '28/02/2025 BY TRF Interest Credit 0.00 267.00 67,882.75 Cr',
 '02/03/2025 TO TRF UPI/Movie Night 1,500.00 0.00 66,382.75 Cr',
 '05/03/2025 BY TRF Salary Credit 0.00 65,000.00 131,382.75 Cr',
 '07/03/2025 TO TRF UPI/Grocery Shopping 3,500.00 0.00 127,882.75 Cr',
 '10/03/2025 TO TRF Rent Payment 25,000.00 0.00 102,882.75 Cr',
 '12/03/2025 TO TRF UPI/Electricity Bill 2,100.00 0.00 100,782.75 Cr',
 '15/03/2025 TO TRF Car Loan EMI 18,500.00 0.00 82,282.75 Cr',
 '18/03/2025 TO TRF UPI/Birthday Gift 2,500.00 0.00 79,782.75 Cr',
 '20/03/2025 TO TRF UPI/Online Shopping 7,250.00 0.00 72,532.75 CrDate Particular Debit Credit Balance',
 '23/03/2025 TO TRF UPI/Dental Appointment 3,000.00 0.00 69,532.75 Cr',
 '25/03/2025 BY TRF Tax Refund 0.00 8,500.00 78,032.75 Cr',
 '28/03/2025 TO TRF UPI/Home Repairs 4,500.00 0.00 73,532.75 Cr',
 '31/03/2025 BY TRF Interest Credit 0.00 290.00 73,822.75 Cr',
 '02/04/2025 TO TRF UPI/Charity Donation 2,000.00 0.00 71,822.75 Cr',
 '05/04/2025 BY TRF Salary Credit 0.00 68,000.00 139,822.75 Cr',
 '07/04/2025 TO TRF UPI/Grocery Shopping 3,800.00 0.00 136,022.75 Cr',
 '10/04/2025 TO TRF Rent Payment 25,000.00 0.00 111,022.75 Cr',
 '12/04/2025 TO TRF UPI/Electricity Bill 2,300.00 0.00 108,722.75 Cr',
 '15/04/2025 TO TRF Credit Card Bill 20,000.00 0.00 88,722.75 Cr',
 '18/04/2025 TO TRF UPI/New Smartphone 15,000.00 0.00 73,722.75 Cr',
 '20/04/2025 TO TRF UPI/W edding Gift 5,000.00 0.00 68,722.75 Cr',
 '23/04/2025 BY TRF UPI/Freelance W ork 0.00 12,000.00 80,722.75 Cr',
 '25/04/2025 TO TRF UPI/Home Appliance 8,000.00 0.00 72,722.75 Cr',
 '28/04/2025 TO TRF UPI/Car Insurance 6,500.00 0.00 66,222.75 Cr',
 '30/04/2025 BY TRF Interest Credit 0.00 261.00 66,483.75 Cr',
 '02/05/2025 TO TRF UPI/W eekend Trip 7,000.00 0.00 59,483.75 Cr',
 '05/05/2025 BY TRF Salary Credit 0.00 68,000.00 127,483.75 Cr',
 '07/05/2025 TO TRF UPI/Grocery Shopping 4,000.00 0.00 123,483.75 Cr',
 '10/05/2025 TO TRF Rent Payment 25,000.00 0.00 98,483.75 Cr',
 '12/05/2025 TO TRF Family V acation Expenses 75,000.00 0.00 23']

In [78]:
# Importing Pandas library
import pandas as pd

## Splitting the transactions

In [80]:
def split_transaction(line):
    # Splits a transaction line into its individual components.

    # Split the line at spaces
    parts = line.split()
    
    # Date is the first part
    date = parts[0]
    
    # Amount is second to last, transaction type is the last part
    cr = parts[-1] 
    balance = parts[-2]  
    total_balance = " ".join(parts[-2:]) 
    credit = parts[-3]  # Credit amount
    debit = parts[-4]  # Debit amount
    
    # Everything in between is the description
    particular = " ".join(parts[1:-4])  # Join the description parts
    
    return [date, particular, debit, credit, total_balance]

# Apply the split_transaction function to each line in data
split_data = [split_transaction(line) for line in pdf_lines_cleaned]
# This line uses a list comprehension to apply the split_transaction function to each line 
# and store the results in the split_data list

# Create a DataFrame with the appropriate columns
df = pd.DataFrame(split_data, columns=['date', 'particular', 'debit', 'credit', 'total_balance'])
# Create a pandas DataFrame using the split_data list and specify the column names

df # printing the df

,date,particular,debit,credit,total_balance
0,01/01/2025,Opening Balance,0.00,0.00,"52,415.75 Cr"
1,02/01/2025,TO TRF UPI/New Year Party Expenses,"3,500.00",0.00,"48,915.75 Cr"
2,05/01/2025,BY TRF Salary Credit,0.00,"65,000.00","113,915.75 Cr"
3,07/01/2025,TO TRF UPI/Grocery Shopping,"2,800.00",0.00,"111,115.75 Cr"
4,10/01/2025,TO TRF Rent Payment,"25,000.00",0.00,"86,115.75 Cr"
5,12/01/2025,TO TRF UPI/Electricity Bill,"1,850.00",0.00,"84,265.75 Cr"
6,15/01/2025,TO TRF Credit Card Bill,"12,500.00",0.00,"71,765.75 Cr"
7,18/01/2025,TO TRF UPI/Dining Out,"2,200.00",0.00,"69,565.75 Cr"
8,20/01/2025,TO TRF UPI/Mobile Recharge,999.00,0.00,"68,566.75 Cr"
9,25/01/2025,TO TRF UPI/Online Shopping,"3,500.00",0.00,"65,066.75 Cr"
10,28/01/2025,TO TRF UPI/Gym Membership,"2,000.00",0.00,"63,066.75 Cr"
11,31/01/2025,BY TRF Interest Credit,0.00,249.00,"63,315.75 Cr"
12,02/02/2025,TO TRF UPI/W eekend Getaway,"5,500.00",0.00,"57,815.75 Cr"
13,05/02/2025,BY TRF Salary Credit,0.00,"65,000.00","122,815.75 Cr"
14,07/02/2025,TO TRF UPI/Grocery Shopping,"3,200.00",0.00,"119,615.75 Cr"
15,10/02/2025,TO TRF Rent Payment,"25,000.00",0.00,"94,615.75 Cr"
16,12/02/2025,TO TRF Insurance Premium,"8,500.00",0.00,"86,115.75 Cr"
17,15/02/2025,TO TRF Credit Card Bill,"15,000.00",0.00,"71,115.75 Cr"
18,18/02/2025,TO TRF UPI/V alentine's Day Gift,"4,000.00",0.00,"67,115.75 Cr"
19,20/02/2025,TO TRF UPI/Car Service,"3,500.00",0.00,"63,615.75 Cr"
20,23/02/2025,BY TRF UPI/Freelance W ork,0.00,"10,000.00","73,615.75 Cr"
21,25/02/2025,TO TRF UPI/Home Decor Items,"6,000.00",0.00,"67,615.75 Cr"
22,28/02/2025,BY TRF Interest Credit,0.00,267.00,"67,882.75 Cr"
23,02/03/2025,TO TRF UPI/Movie Night,"1,500.00",0.00,"66,382.75 Cr"
24,05/03/2025,BY TRF Salary Credit,0.00,"65,000.00","131,382.75 Cr"
25,07/03/2025,TO TRF UPI/Grocery Shopping,"3,500.00",0.00,"127,882.75 Cr"
26,10/03/2025,TO TRF Rent Payment,"25,000.00",0.00,"102,882.75 Cr"
27,12/03/2025,TO TRF UPI/Electricity Bill,"2,100.00",0.00,"100,782.75 Cr"
28,15/03/2025,TO TRF Car Loan EMI,"18,500.00",0.00,"82,282.75 Cr"
29,18/03/2025,TO TRF UPI/Birthday Gift,"2,500.00",0.00,"79,782.75 Cr"
30,20/03/2025,"TO TRF UPI/Online Shopping 7,250.00 0.00 72,53...",Particular,Debit,Credit Balance
31,23/03/2025,TO TRF UPI/Dental Appointment,"3,000.00",0.00,"69,532.75 Cr"
32,25/03/2025,BY TRF Tax Refund,0.00,"8,500.00","78,032.75 Cr"
33,28/03/2025,TO TRF UPI/Home Repairs,"4,500.00",0.00,"73,532.75 Cr"
34,31/03/2025,BY TRF Interest Credit,0.00,290.00,"73,822.75 Cr"
35,02/04/2025,TO TRF UPI/Charity Donation,"2,000.00",0.00,"71,822.75 Cr"
36,05/04/2025,BY TRF Salary Credit,0.00,"68,000.00","139,822.75 Cr"
37,07/04/2025,TO TRF UPI/Grocery Shopping,"3,800.00",0.00,"136,022.75 Cr"
38,10/04/2025,TO TRF Rent Payment,"25,000.00",0.00,"111,022.75 Cr"
39,12/04/2025,TO TRF UPI/Electricity Bill,"2,300.00",0.00,"108,722.75 Cr"
40,15/04/2025,TO TRF Credit Card Bill,"20,000.00",0.00,"88,722.75 Cr"
41,18/04/2025,TO TRF UPI/New Smartphone,"15,000.00",0.00,"73,722.75 Cr"
42,20/04/2025,TO TRF UPI/W edding Gift,"5,000.00",0.00,"68,722.75 Cr"
43,23/04/2025,BY TRF UPI/Freelance W ork,0.00,"12,000.00","80,722.75 Cr"
44,25/04/2025,TO TRF UPI/Home Appliance,"8,000.00",0.00,"72,722.75 Cr"
45,28/04/2025,TO TRF UPI/Car Insurance,"6,500.00",0.00,"66,222.75 Cr"
46,30/04/2025,BY TRF Interest Credit,0.00,261.00,"66,483.75 Cr"
47,02/05/2025,TO TRF UPI/W eekend Trip,"7,000.00",0.00,"59,483.75 Cr"
48,05/05/2025,BY TRF Salary Credit,0.00,"68,000.00","127,483.75 Cr"
49,07/05/2025,TO TRF UPI/Grocery Shopping,"4,000.00",0.00,"123,483.75 Cr"
50,10/05/2025,TO TRF Rent Payment,"25,000.00",0.00,"98,483.75 Cr"
51,12/05/2025,TO TRF Family V acation,Expenses,"75,000.00",0.00 23

#### In the above df we can see that at the 30th index value is overlapping with the next page's title so in next we are changing that

In [82]:
#  Update the values at index 30 
df['particular'][30] = 'TO TRF UPI/Online Shopping'
df['debit'][30] = '7,250.00'
df['credit'][30] = '0.00'
df['total_balance'][30] = '72,532.75 Cr'

In [83]:
#  Update the values at index 30 
df['particular'][51] = 'TO TRF Family Vacation Expenses'
df['debit'][51] = '75,000.00'
df['credit'][51] = '0.00'
df['total_balance'][51] = '23 Cr'

In [84]:
# converting debit and credit columns with float data type
df['debit'] = df['debit'].str.replace(',', '').astype(float)
df['credit'] = df['credit'].str.replace(',', '').astype(float)

df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')

## Generating unique id to each transaction

In [86]:
# As expected in assignment we don't have unique_id in pdf file so we are creating that 

import uuid

# Function to generate unique IDs
def generate_unique_id():
    return str(uuid.uuid4())

# Apply the function to create a list of unique IDs
df['unique_id'] = [generate_unique_id() for _ in range(len(df))]

# Ensure DataFrame is processed from the first row
df.reset_index(drop=True, inplace=True)

In [87]:
# requirement from the pdf we are creating single column for the debit and credit 

df['transaction_type'] = df.apply(lambda row: 'Credit' if row['debit'] == 0.00 else 'Debit', axis=1)

df['amount'] = df.apply(lambda row: row['debit'] if row['credit'] == 0.00 else row['credit'], axis=1)
df
df1 = pd.DataFrame(df, columns=['unique_id','date', 'particular', 'amount', 'transaction_type'])
df1

,unique_id,date,particular,amount,transaction_type
0,7545e799-9d17-448a-b197-49f23547dfe8,2025-01-01,Opening Balance,0.0,Credit
1,315532e7-8304-45a9-b2ff-decd00dabde6,2025-01-02,TO TRF UPI/New Year Party Expenses,3500.0,Debit
2,c9bc249a-bde8-4758-b472-c9a2616ed60d,2025-01-05,BY TRF Salary Credit,65000.0,Credit
3,a5a5643d-0459-4094-a493-a30e972a7e19,2025-01-07,TO TRF UPI/Grocery Shopping,2800.0,Debit
4,bc1169d6-4478-456f-827e-42d2354f3ab4,2025-01-10,TO TRF Rent Payment,25000.0,Debit
5,86f422e5-2c45-4aaf-95dd-517382788cdf,2025-01-12,TO TRF UPI/Electricity Bill,1850.0,Debit
6,50fd8751-fa39-4143-b81e-a813e76171d3,2025-01-15,TO TRF Credit Card Bill,12500.0,Debit
7,849ee0f3-f73f-4d44-a324-2b25b844072c,2025-01-18,TO TRF UPI/Dining Out,2200.0,Debit
8,836b85df-9900-4455-9e84-45debbfab4bb,2025-01-20,TO TRF UPI/Mobile Recharge,999.0,Debit
9,1a74b114-1a50-4a88-837f-0bc53ca8f90e,2025-01-25,TO TRF UPI/Online Shopping,3500.0,Debit
10,038985f6-6cf4-4506-b680-3a0db807aef3,2025-01-28,TO TRF UPI/Gym Membership,2000.0,Debit
11,4621ca51-8ea4-4d76-90bd-936b323954a8,2025-01-31,BY TRF Interest Credit,249.0,Credit
12,966c898d-abeb-4228-988a-8bf47514b0a4,2025-02-02,TO TRF UPI/W eekend Getaway,5500.0,Debit
13,c33fba6e-e433-4b41-8538-8d34cd1ea323,2025-02-05,BY TRF Salary Credit,65000.0,Credit
14,adbdd520-369b-484c-8b23-5d38679416b6,2025-02-07,TO TRF UPI/Grocery Shopping,3200.0,Debit
15,c1d776ba-28c9-49e7-8313-6f6b92114c0e,2025-02-10,TO TRF Rent Payment,25000.0,Debit
16,f54d8dc0-125a-4ef7-a4f8-06161ecdf6b1,2025-02-12,TO TRF Insurance Premium,8500.0,Debit
17,bd666215-5d25-4edc-a57d-be1f24d227b6,2025-02-15,TO TRF Credit Card Bill,15000.0,Debit
18,6b6dd0f6-a63c-4608-9c7a-d3d1a35baa7b,2025-02-18,TO TRF UPI/V alentine's Day Gift,4000.0,Debit
19,fde17107-0a48-4c19-8305-ce788ca9d22b,2025-02-20,TO TRF UPI/Car Service,3500.0,Debit
20,64641d12-be74-47ef-9926-2bbe833e4803,2025-02-23,BY TRF UPI/Freelance W ork,10000.0,Credit
21,996f7449-eed5-4b26-afff-0371d88ff047,2025-02-25,TO TRF UPI/Home Decor Items,6000.0,Debit
22,01f402a1-fd99-4ba8-9788-1d003a5759cc,2025-02-28,BY TRF Interest Credit,267.0,Credit
23,16b03913-fdc9-4c10-8eb5-51265767f22f,2025-03-02,TO TRF UPI/Movie Night,1500.0,Debit
24,3002c949-07e6-440b-b680-25b6d1cac8e3,2025-03-05,BY TRF Salary Credit,65000.0,Credit
25,1b51723a-9038-484d-b2fb-f7dfee3de042,2025-03-07,TO TRF UPI/Grocery Shopping,3500.0,Debit
26,76cbf17d-a115-4c78-9832-1b253b78656d,2025-03-10,TO TRF Rent Payment,25000.0,Debit
27,63362190-f9c9-4f90-9c83-508f88c17c8e,2025-03-12,TO TRF UPI/Electricity Bill,2100.0,Debit
28,44bdb372-830a-4e43-91d9-6e29726281cc,2025-03-15,TO TRF Car Loan EMI,18500.0,Debit
29,25b18bfd-52d0-4beb-b757-48cb3939dc2d,2025-03-18,TO TRF UPI/Birthday Gift,2500.0,Debit
30,8523c037-c46f-42cc-beb8-04047dbcbfbd,2025-03-20,TO TRF UPI/Online Shopping,7250.0,Debit
31,82d5f166-a0c0-401b-ae6d-9be721f7dbe2,2025-03-23,TO TRF UPI/Dental Appointment,3000.0,Debit
32,c7fea10b-d71f-4b3c-93c2-1c644e12f941,2025-03-25,BY TRF Tax Refund,8500.0,Credit
33,4665aad7-a6bb-4108-aeb9-6b7c3e2c909e,2025-03-28,TO TRF UPI/Home Repairs,4500.0,Debit
34,e16a69fb-8be1-4992-8e94-34bfeb9fadd9,2025-03-31,BY TRF Interest Credit,290.0,Credit
35,6864ca7e-4653-4710-8601-fab8663cdc34,2025-04-02,TO TRF UPI/Charity Donation,2000.0,Debit
36,0a29da51-f090-4207-a230-5b305522bd8b,2025-04-05,BY TRF Salary Credit,68000.0,Credit
37,47b8692f-83c7-4c3c-b2b6-ba719d51166f,2025-04-07,TO TRF UPI/Grocery Shopping,3800.0,Debit
38,3dee9166-f33e-4c09-854c-4f1cde443973,2025-04-10,TO TRF Rent Payment,25000.0,Debit
39,31b5567e-27e4-4465-89a9-add6c54cbe35,2025-04-12,TO TRF UPI/Electricity Bill,2300.0,Debit
40,0114c932-a4b4-44dc-966b-8a8e0477b471,2025-04-15,TO TRF Credit Card Bill,20000.0,Debit
41,215e7a76-ea55-49fa-b33d-25f22883ca08,2025-04-18,TO TRF UPI/New Smartphone,15000.0,Debit
42,7a527f3b-eb64-4cc9-baa3-0449a60c0c66,2025-04-20,TO TRF UPI/W edding Gift,5000.0,Debit
43,b81e6244-6dcc-4435-b39a-aac8920c5111,2025-04-23,BY TRF UPI/Freelance W ork,12000.0,Credit
44,2e411280-c187-404d-978d-223e0e1802f9,2025-04-25,TO TRF UPI/Home Appliance,8000.0,Debit
45,f31c8728-9014-40ad-b205-4df257797ace,2025-04-28,TO TRF UPI/Car Insurance,6500.0,Debit
46,e2f40ec8-6823-4341-ac04-2dc7826a0fca,2025-04-30,BY TRF Interest Credit,261.0,Credit
47,ae1a9124-650f-4fc4-9a18-07e819b21dae,2025-05-02,TO TRF UPI/W eekend Trip,7000.0,Debit
48,85a00b73-c794-4798-b61f-371caf871140,2025-05-05,BY TRF Salary Credit,68000.0,Credit
49,2427a0e5-ef27-45c7-8758-5c45056f6aca,2025-05-07,TO TRF UPI/Grocery Shopping,4000.0,Debit
50,881e7465-1360-4861-96dd-39526450e294,2025-05-10,TO TRF Rent Payment,25000.0,Debit
51,f6fea3a2-75f9-48d6-80b1-13eba173a3be,2025-05-12,TO TRF Family Vacation Expenses,75000.0,Debit

In [88]:
import json

# Define the JSON structure as a Python dictionary
json_data = {
    "start_row":1,
    "columns": {
        "unique_id":"unique_id",
        "date": "date",
        "description": "description",
        "amount": "amount",
        "transaction_type": "transaction_type"
    }
}

# Convert the dictionary to a JSON string (optional)
json_string = json.dumps(json_data, indent=4)

# Display the JSON string
print("JSON String:")
print(json_string)

# If you need to save the JSON object to a file
with open('data_config.json', 'w') as file:
    json.dump(json_data, file, indent=4)

JSON String:
{
    "start_row": 1,
    "columns": {
        "unique_id": "unique_id",
        "date": "date",
        "description": "description",
        "amount": "amount",
        "transaction_type": "transaction_type"
    }
}

In [89]:
with open('data_config.json', 'r') as file:
    config = json.load(file)

start_row = config['start_row']
columns_mapping = config['columns']

In [90]:
df1.rename(columns=columns_mapping, inplace=True)

# Ensure the start row is properly accounted for
df1 = df1.iloc[start_row - 1:].reset_index(drop=True)

# Check the DataFrame
df1

,unique_id,date,particular,amount,transaction_type
0,7545e799-9d17-448a-b197-49f23547dfe8,2025-01-01,Opening Balance,0.0,Credit
1,315532e7-8304-45a9-b2ff-decd00dabde6,2025-01-02,TO TRF UPI/New Year Party Expenses,3500.0,Debit
2,c9bc249a-bde8-4758-b472-c9a2616ed60d,2025-01-05,BY TRF Salary Credit,65000.0,Credit
3,a5a5643d-0459-4094-a493-a30e972a7e19,2025-01-07,TO TRF UPI/Grocery Shopping,2800.0,Debit
4,bc1169d6-4478-456f-827e-42d2354f3ab4,2025-01-10,TO TRF Rent Payment,25000.0,Debit
5,86f422e5-2c45-4aaf-95dd-517382788cdf,2025-01-12,TO TRF UPI/Electricity Bill,1850.0,Debit
6,50fd8751-fa39-4143-b81e-a813e76171d3,2025-01-15,TO TRF Credit Card Bill,12500.0,Debit
7,849ee0f3-f73f-4d44-a324-2b25b844072c,2025-01-18,TO TRF UPI/Dining Out,2200.0,Debit
8,836b85df-9900-4455-9e84-45debbfab4bb,2025-01-20,TO TRF UPI/Mobile Recharge,999.0,Debit
9,1a74b114-1a50-4a88-837f-0bc53ca8f90e,2025-01-25,TO TRF UPI/Online Shopping,3500.0,Debit
10,038985f6-6cf4-4506-b680-3a0db807aef3,2025-01-28,TO TRF UPI/Gym Membership,2000.0,Debit
11,4621ca51-8ea4-4d76-90bd-936b323954a8,2025-01-31,BY TRF Interest Credit,249.0,Credit
12,966c898d-abeb-4228-988a-8bf47514b0a4,2025-02-02,TO TRF UPI/W eekend Getaway,5500.0,Debit
13,c33fba6e-e433-4b41-8538-8d34cd1ea323,2025-02-05,BY TRF Salary Credit,65000.0,Credit
14,adbdd520-369b-484c-8b23-5d38679416b6,2025-02-07,TO TRF UPI/Grocery Shopping,3200.0,Debit
15,c1d776ba-28c9-49e7-8313-6f6b92114c0e,2025-02-10,TO TRF Rent Payment,25000.0,Debit
16,f54d8dc0-125a-4ef7-a4f8-06161ecdf6b1,2025-02-12,TO TRF Insurance Premium,8500.0,Debit
17,bd666215-5d25-4edc-a57d-be1f24d227b6,2025-02-15,TO TRF Credit Card Bill,15000.0,Debit
18,6b6dd0f6-a63c-4608-9c7a-d3d1a35baa7b,2025-02-18,TO TRF UPI/V alentine's Day Gift,4000.0,Debit
19,fde17107-0a48-4c19-8305-ce788ca9d22b,2025-02-20,TO TRF UPI/Car Service,3500.0,Debit
20,64641d12-be74-47ef-9926-2bbe833e4803,2025-02-23,BY TRF UPI/Freelance W ork,10000.0,Credit
21,996f7449-eed5-4b26-afff-0371d88ff047,2025-02-25,TO TRF UPI/Home Decor Items,6000.0,Debit
22,01f402a1-fd99-4ba8-9788-1d003a5759cc,2025-02-28,BY TRF Interest Credit,267.0,Credit
23,16b03913-fdc9-4c10-8eb5-51265767f22f,2025-03-02,TO TRF UPI/Movie Night,1500.0,Debit
24,3002c949-07e6-440b-b680-25b6d1cac8e3,2025-03-05,BY TRF Salary Credit,65000.0,Credit
25,1b51723a-9038-484d-b2fb-f7dfee3de042,2025-03-07,TO TRF UPI/Grocery Shopping,3500.0,Debit
26,76cbf17d-a115-4c78-9832-1b253b78656d,2025-03-10,TO TRF Rent Payment,25000.0,Debit
27,63362190-f9c9-4f90-9c83-508f88c17c8e,2025-03-12,TO TRF UPI/Electricity Bill,2100.0,Debit
28,44bdb372-830a-4e43-91d9-6e29726281cc,2025-03-15,TO TRF Car Loan EMI,18500.0,Debit
29,25b18bfd-52d0-4beb-b757-48cb3939dc2d,2025-03-18,TO TRF UPI/Birthday Gift,2500.0,Debit
30,8523c037-c46f-42cc-beb8-04047dbcbfbd,2025-03-20,TO TRF UPI/Online Shopping,7250.0,Debit
31,82d5f166-a0c0-401b-ae6d-9be721f7dbe2,2025-03-23,TO TRF UPI/Dental Appointment,3000.0,Debit
32,c7fea10b-d71f-4b3c-93c2-1c644e12f941,2025-03-25,BY TRF Tax Refund,8500.0,Credit
33,4665aad7-a6bb-4108-aeb9-6b7c3e2c909e,2025-03-28,TO TRF UPI/Home Repairs,4500.0,Debit
34,e16a69fb-8be1-4992-8e94-34bfeb9fadd9,2025-03-31,BY TRF Interest Credit,290.0,Credit
35,6864ca7e-4653-4710-8601-fab8663cdc34,2025-04-02,TO TRF UPI/Charity Donation,2000.0,Debit
36,0a29da51-f090-4207-a230-5b305522bd8b,2025-04-05,BY TRF Salary Credit,68000.0,Credit
37,47b8692f-83c7-4c3c-b2b6-ba719d51166f,2025-04-07,TO TRF UPI/Grocery Shopping,3800.0,Debit
38,3dee9166-f33e-4c09-854c-4f1cde443973,2025-04-10,TO TRF Rent Payment,25000.0,Debit
39,31b5567e-27e4-4465-89a9-add6c54cbe35,2025-04-12,TO TRF UPI/Electricity Bill,2300.0,Debit
40,0114c932-a4b4-44dc-966b-8a8e0477b471,2025-04-15,TO TRF Credit Card Bill,20000.0,Debit
41,215e7a76-ea55-49fa-b33d-25f22883ca08,2025-04-18,TO TRF UPI/New Smartphone,15000.0,Debit
42,7a527f3b-eb64-4cc9-baa3-0449a60c0c66,2025-04-20,TO TRF UPI/W edding Gift,5000.0,Debit
43,b81e6244-6dcc-4435-b39a-aac8920c5111,2025-04-23,BY TRF UPI/Freelance W ork,12000.0,Credit
44,2e411280-c187-404d-978d-223e0e1802f9,2025-04-25,TO TRF UPI/Home Appliance,8000.0,Debit
45,f31c8728-9014-40ad-b205-4df257797ace,2025-04-28,TO TRF UPI/Car Insurance,6500.0,Debit
46,e2f40ec8-6823-4341-ac04-2dc7826a0fca,2025-04-30,BY TRF Interest Credit,261.0,Credit
47,ae1a9124-650f-4fc4-9a18-07e819b21dae,2025-05-02,TO TRF UPI/W eekend Trip,7000.0,Debit
48,85a00b73-c794-4798-b61f-371caf871140,2025-05-05,BY TRF Salary Credit,68000.0,Credit
49,2427a0e5-ef27-45c7-8758-5c45056f6aca,2025-05-07,TO TRF UPI/Grocery Shopping,4000.0,Debit
50,881e7465-1360-4861-96dd-39526450e294,2025-05-10,TO TRF Rent Payment,25000.0,Debit
51,f6fea3a2-75f9-48d6-80b1-13eba173a3be,2025-05-12,TO TRF Family Vacation Expenses,75000.0,Debit

## Cnnecting to the Mysql server

In [92]:
import mysql.connector

def create_database_and_table():
    connection = mysql.connector.connect(
        host='localhost',
        user='root',
        password='SQL123'
    )
    cursor = connection.cursor()
    
    # Create database
    cursor.execute("CREATE DATABASE IF NOT EXISTS bank")
    
    # Use the database
    cursor.execute("USE bank")
    
    # Create table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS transactions (
            unique_id CHAR(36) PRIMARY KEY,
            date DATE,
            description TEXT,
            amount DECIMAL(10, 2),
            transaction_type ENUM('CREDIT', 'DEBIT')
        )
    ''')
    
    cursor.close()
    connection.close()

create_database_and_table()

In [93]:
import pandas as pd

def connect_to_db():
    return mysql.connector.connect(
        host='localhost',
        user='root',
        password='SQL123',
        database='bank'
    )

def insert_dataframe(df):
    connection = connect_to_db()
    cursor = connection.cursor()
    
    # Insert each row into the database
    for _, row in df.iterrows():
        cursor.execute('''
            INSERT INTO transactions (unique_id, date, description, amount, transaction_type)
            VALUES (%s, %s, %s, %s, %s)
        ''', (row['unique_id'], row['date'], row['particular'], row['amount'], row['transaction_type']))
    
    connection.commit()
    cursor.close()
    connection.close()

insert_dataframe(df1)

## As mentioned in requirements we converted dataframe into json file

In [95]:
df1.to_json('transaction_output.json', orient='records', lines=True)

print("DataFrame has been saved to 'transaction_output.json'")

DataFrame has been saved to 'transaction_output.json'